// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/worker/login": {
    params: {};
  };
  "/patient/login": {
    params: {};
  };
  "/patient/dashboard": {
    params: {};
  };
  "/patient/appointments": {
    params: {};
  };
  "/patient/appointments/new": {
    params: {};
  };
  "/patient/appointments/:id/questionnaire": {
    params: {
      "id": string;
    };
  };
  "/patient/consultation/:id": {
    params: {
      "id": string;
    };
  };
  "/patient/messages": {
    params: {};
  };
  "/worker/doctor/dashboard": {
    params: {};
  };
  "/worker/doctor/schedule": {
    params: {};
  };
  "/worker/doctor/consultation/:id": {
    params: {
      "id": string;
    };
  };
  "/worker/doctor/patients": {
    params: {};
  };
  "/worker/doctor/medical-records/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/worker/operator/dashboard": {
    params: {};
  };
  "/worker/operator/assignment-board": {
    params: {};
  };
  "/worker/admin/doctors": {
    params: {};
  };
  "/worker/admin/doctors/:id/schedule/edit": {
    params: {
      "id": string;
    };
  };
  "/worker/dashboard": {
    params: {};
  };
  "/worker/consultation/:id": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/worker/login" | "/patient/login" | "/patient/dashboard" | "/patient/appointments" | "/patient/appointments/new" | "/patient/appointments/:id/questionnaire" | "/patient/consultation/:id" | "/patient/messages" | "/worker/doctor/dashboard" | "/worker/doctor/schedule" | "/worker/doctor/consultation/:id" | "/worker/doctor/patients" | "/worker/doctor/medical-records/:id/edit" | "/worker/operator/dashboard" | "/worker/operator/assignment-board" | "/worker/admin/doctors" | "/worker/admin/doctors/:id/schedule/edit" | "/worker/dashboard" | "/worker/consultation/:id";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/worker/login.tsx": {
    id: "routes/worker/login";
    page: "/worker/login";
  };
  "routes/patient/login.tsx": {
    id: "routes/patient/login";
    page: "/patient/login";
  };
  "routes/patient/dashboard.tsx": {
    id: "routes/patient/dashboard";
    page: "/patient/dashboard";
  };
  "routes/patient/appointments.tsx": {
    id: "routes/patient/appointments";
    page: "/patient/appointments";
  };
  "routes/patient/appointments/new.tsx": {
    id: "routes/patient/appointments/new";
    page: "/patient/appointments/new";
  };
  "routes/patient/appointments/$id.questionnaire.tsx": {
    id: "routes/patient/appointments/$id.questionnaire";
    page: "/patient/appointments/:id/questionnaire";
  };
  "routes/patient/consultation/$id.tsx": {
    id: "routes/patient/consultation/$id";
    page: "/patient/consultation/:id";
  };
  "routes/patient/messages.tsx": {
    id: "routes/patient/messages";
    page: "/patient/messages";
  };
  "routes/worker/doctor/dashboard.tsx": {
    id: "routes/worker/doctor/dashboard";
    page: "/worker/doctor/dashboard";
  };
  "routes/worker.doctor.schedule.tsx": {
    id: "routes/worker.doctor.schedule";
    page: "/worker/doctor/schedule";
  };
  "routes/worker/doctor/consultation/$id.tsx": {
    id: "routes/worker/doctor/consultation/$id";
    page: "/worker/doctor/consultation/:id";
  };
  "routes/worker/doctor/patients.tsx": {
    id: "routes/worker/doctor/patients";
    page: "/worker/doctor/patients";
  };
  "routes/worker/doctor/medical-records/$id.edit.tsx": {
    id: "routes/worker/doctor/medical-records/$id.edit";
    page: "/worker/doctor/medical-records/:id/edit";
  };
  "routes/worker/operator/dashboard.tsx": {
    id: "routes/worker/operator/dashboard";
    page: "/worker/operator/dashboard";
  };
  "routes/worker/operator/assignment-board.tsx": {
    id: "routes/worker/operator/assignment-board";
    page: "/worker/operator/assignment-board";
  };
  "routes/worker/admin/doctors.tsx": {
    id: "routes/worker/admin/doctors";
    page: "/worker/admin/doctors";
  };
  "routes/worker/admin/doctors/$id.schedule.edit.tsx": {
    id: "routes/worker/admin/doctors/$id.schedule.edit";
    page: "/worker/admin/doctors/:id/schedule/edit";
  };
  "routes/worker/dashboard.tsx": {
    id: "routes/worker/dashboard";
    page: "/worker/dashboard";
  };
  "routes/worker/consultation/$id.tsx": {
    id: "routes/worker/consultation/$id";
    page: "/worker/consultation/:id";
  };
};